AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 224
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
    - aircraft
    DATASET_ROOTS:
    - /home/datasets/fgvc-aircraft-2013b/converted/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 1
      MIN_EXAMPLES_IN_CLASS: 17
      NUM_QUERY: 7
      NUM_SUPPORT: 10
      NUM_TASKS_PER_EPOCH: 2000
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: DINO_v2
  BACKBONE_HYPERPARAMETERS:
  - dinov2_vitb14_reg
  CLASSIFIER: finetune
  CLASSIFIER_PARAMETERS:
  - 100
  - 100
  - 30
  - 0.0001
  - 0.1
  - false
  - false
  - fc
  NAME: evaluation
  TYPE: fewshot_finetune
OUTPUT: ../new_metadataset_result
